# config/settings.yaml

algorithm:
  name: "NSGA-II"
  population_size: 80
  generations: 100
  crossover_probability: 0.9
  mutation_probability: 0.2
  selection: "tournament"
  tournament_size: 2

project:
  input_file: "data/rempsp/program.xml"
  output_dir: "results/"
  log_level: "INFO"
  seed: 42
  resource_overflow_penalty: 1e6

file:
  j30_fil_num: 50
  j60_fil_num: 20